// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlAgdELkN015I6aqfV4NxOSzT-A-gB83k',
    appId: '1:997357711398:web:09860fa3ecc837090f76e7',
    messagingSenderId: '997357711398',
    projectId: 'appmobileadtec',
    authDomain: 'appmobileadtec.firebaseapp.com',
    storageBucket: 'appmobileadtec.firebasestorage.app',
    measurementId: 'G-RR01DPZQ69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJf6ypky9Ta1hFE_YsDhoBM5O3OkyKBpw',
    appId: '1:997357711398:android:b4942a2fae6f04c20f76e7',
    messagingSenderId: '997357711398',
    projectId: 'appmobileadtec',
    storageBucket: 'appmobileadtec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRBvrX4lyMCg1iL0xqDyFRQVBNV69j-Es',
    appId: '1:997357711398:ios:b886714f9f797a130f76e7',
    messagingSenderId: '997357711398',
    projectId: 'appmobileadtec',
    storageBucket: 'appmobileadtec.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRBvrX4lyMCg1iL0xqDyFRQVBNV69j-Es',
    appId: '1:997357711398:ios:b886714f9f797a130f76e7',
    messagingSenderId: '997357711398',
    projectId: 'appmobileadtec',
    storageBucket: 'appmobileadtec.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlAgdELkN015I6aqfV4NxOSzT-A-gB83k',
    appId: '1:997357711398:web:0b4e8d9156e396570f76e7',
    messagingSenderId: '997357711398',
    projectId: 'appmobileadtec',
    authDomain: 'appmobileadtec.firebaseapp.com',
    storageBucket: 'appmobileadtec.firebasestorage.app',
    measurementId: 'G-YQTEZ942VG',
  );
}
